name: Update README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: npm run update-readme
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
    - run: |
        git config user.name "codegeekery"
        git config user.email "85375414+codegeekery@users.noreply.github.com"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update README with latest info"
        git push origin production
