name: Update README with Latest Posts

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install axios

      - name: Fetch latest posts from the API
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          SECRET_KEY="${{ secrets.SECRET_KEY }}"

          HMAC_KEY=$(echo -n "$SECRET_KEY" | openssl dgst -sha256 -hmac "$SECRET_KEY" | sed 's/^.* //')

          # Realiza la solicitud a la API y guarda la respuesta en latest-posts.json
          curl -H "X-CODEGEEKERY: $HMAC_KEY" "https://italiano-cambridge-yeah-affected.trycloudflare.com/api/latest-post"
