name: Update README

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - production

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run script to update README
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: npm run update-readme

      - name: Commit and push if changed
        run: |
          git config user.name "codegeekery"
          git config user.email "85375414+codegeekery@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
          git push origin production
