name: Update README with Latest Articles

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm ci

    - name: Compile TypeScript
      run: npx tsc

    - name: Fetch latest articles JSON
      run: |
        curl -H "X-CODEGEEKERY: ${{ secrets.SECRET_KEY }}" -o ./dist/post-latest.json "https://www.codegeekery.com/api/latest"

    - name: Run script to update README.md
      run: node ./dist/updates-readme.js

    - name: Pull latest changes
      run: |
        git pull origin main

    - name: Commit and push changes
      run: |
        git config --global user.name "codegeekery"
        git config --global user.email "85375414+codegeekery@users.noreply.github.com"
        git add README.md ./dist/*
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
        git push origin main


